#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-devtools
Version  : 0.1.9
Release  : 9
URL      : https://rubygems.org/downloads/devtools-0.1.9.gem
Source0  : https://rubygems.org/downloads/devtools-0.1.9.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-actionpack
BuildRequires : rubygem-actionview
BuildRequires : rubygem-activesupport
BuildRequires : rubygem-builder
BuildRequires : rubygem-bundler
BuildRequires : rubygem-erubis
BuildRequires : rubygem-i18n
BuildRequires : rubygem-loofah
BuildRequires : rubygem-mini_portile
BuildRequires : rubygem-minitest
BuildRequires : rubygem-nokogiri
BuildRequires : rubygem-rack
BuildRequires : rubygem-rack-test
BuildRequires : rubygem-rails
BuildRequires : rubygem-rails-deprecated_sanitizer
BuildRequires : rubygem-rails-dom-testing
BuildRequires : rubygem-rails-html-sanitizer
BuildRequires : rubygem-railties
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec-its
BuildRequires : rubygem-sqlite3
BuildRequires : rubygem-thor
BuildRequires : rubygem-thread_safe
BuildRequires : rubygem-tzinfo

%description
# devtools
[![Build Status](https://img.shields.io/circleci/project/mbj/devtools.svg)](https://circleci.com/gh/mbj/devtools/tree/master)
[![Dependency Status](https://gemnasium.com/mbj/devtools.png)](https://gemnasium.com/mbj/devtools)
[![Code Climate](https://codeclimate.com/github/datamapper/devtools.png)](https://codeclimate.com/github/datamapper/devtools)
<!-- [![Code Climate](https://codeclimate.com/github/mbj/devtools.png)](https://codeclimate.com/github/mbj/devtools) -->

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n devtools-0.1.9
gem spec %{SOURCE0} -l --ruby > rubygem-devtools.gemspec

%build
export LANG=C
gem build rubygem-devtools.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
devtools-0.1.9.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/devtools-0.1.9.gem
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/.rspec
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/.rubocop.yml
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/.ruby-gemset
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/README.md
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/circle.yml
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/config/devtools.yml
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/config/flay.yml
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/config/flog.yml
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/config/mutant.yml
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/config/reek.yml
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/config/rubocop.yml
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/config/yardstick.yml
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/devtools.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/lib/devtools.rb
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/lib/devtools/config.rb
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/lib/devtools/flay.rb
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/lib/devtools/project.rb
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/lib/devtools/project/initializer.rb
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/lib/devtools/project/initializer/rake.rb
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/lib/devtools/project/initializer/rspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/lib/devtools/rake/flay.rb
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/lib/devtools/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/shared/spec/shared/abstract_type_behavior.rb
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/shared/spec/shared/command_method_behavior.rb
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/shared/spec/shared/each_method_behaviour.rb
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/shared/spec/shared/hash_method_behavior.rb
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/shared/spec/shared/idempotent_method_behavior.rb
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/shared/spec/support/ice_nine_config.rb
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/spec/integration/devtools/rake/flay/verify_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/spec/unit/devtools/config/yardstick_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/spec/unit/devtools/config_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/spec/unit/devtools/flay/file_list/call_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/spec/unit/devtools/flay/scale/flay_report_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/spec/unit/devtools/flay/scale/measure_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/spec/unit/devtools/project/initializer/rake_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/spec/unit/devtools/project/initializer/rspec_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/spec/unit/devtools/project_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/spec/unit/devtools_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/tasks/metrics/ci.rake
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/tasks/metrics/coverage.rake
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/tasks/metrics/flay.rake
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/tasks/metrics/flog.rake
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/tasks/metrics/mutant.rake
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/tasks/metrics/reek.rake
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/tasks/metrics/rubocop.rake
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/tasks/metrics/yardstick.rake
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/tasks/spec.rake
/usr/lib64/ruby/gems/2.3.0/gems/devtools-0.1.9/tasks/yard.rake
/usr/lib64/ruby/gems/2.3.0/specifications/devtools-0.1.9.gemspec
