#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-devtools
Version  : 0.0.1
Release  : 2
URL      : https://rubygems.org/downloads/devtools-0.0.1.gem
Source0  : https://rubygems.org/downloads/devtools-0.0.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-actionpack
BuildRequires : rubygem-actionview
BuildRequires : rubygem-activesupport
BuildRequires : rubygem-builder
BuildRequires : rubygem-bundler
BuildRequires : rubygem-erubis
BuildRequires : rubygem-i18n
BuildRequires : rubygem-loofah
BuildRequires : rubygem-mini_portile
BuildRequires : rubygem-minitest
BuildRequires : rubygem-nokogiri
BuildRequires : rubygem-rack
BuildRequires : rubygem-rack-test
BuildRequires : rubygem-rails
BuildRequires : rubygem-rails-deprecated_sanitizer
BuildRequires : rubygem-rails-dom-testing
BuildRequires : rubygem-rails-html-sanitizer
BuildRequires : rubygem-railties
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-sqlite3
BuildRequires : rubygem-thor
BuildRequires : rubygem-thread_safe
BuildRequires : rubygem-tzinfo

%description
# Devtools
## Description
Devtools is a Rails engine for doing useful things in development &
testing.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n devtools-0.0.1
gem spec %{SOURCE0} -l --ruby > rubygem-devtools.gemspec

%build
gem build rubygem-devtools.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
devtools-0.0.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/devtools-0.0.1.gem
/usr/lib64/ruby/gems/2.2.0/doc/devtools-0.0.1/ri/Devtools/cdesc-Devtools.ri
/usr/lib64/ruby/gems/2.2.0/doc/devtools-0.0.1/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/devtools-0.0.1/ri/lib/tasks/page-devtools_tasks_rake.ri
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/README.md
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/lib/devtools.rb
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/lib/devtools/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/lib/tasks/devtools_tasks.rake
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/devtools_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/README.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/app/assets/javascripts/application.js
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/app/assets/stylesheets/application.css
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/app/controllers/application_controller.rb
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/app/helpers/application_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/app/views/layouts/application.html.erb
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/config.ru
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/config/application.rb
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/config/boot.rb
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/config/database.yml
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/config/environment.rb
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/config/environments/development.rb
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/config/environments/production.rb
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/config/environments/test.rb
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/config/initializers/backtrace_silencers.rb
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/config/initializers/inflections.rb
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/config/initializers/mime_types.rb
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/config/initializers/secret_token.rb
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/config/initializers/session_store.rb
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/config/initializers/wrap_parameters.rb
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/config/locales/en.yml
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/config/routes.rb
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/db/test.sqlite3
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/log/test.log
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/public/404.html
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/public/422.html
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/public/500.html
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/public/favicon.ico
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/dummy/script/rails
/usr/lib64/ruby/gems/2.2.0/gems/devtools-0.0.1/test/test_helper.rb
/usr/lib64/ruby/gems/2.2.0/specifications/devtools-0.0.1.gemspec
